### ISSUE TITLE
generate variable PLATES without file plates_to_process.txt

### ISSUE THREAD

**Issue by cells2numbers** [cytomining/profiling-handbook#1]
We create the variable ${PLATES} in section [3.4](https://cytomining.github.io/profiling-handbook/setup-pipelines-and-images.html#create-list-of-plates) manually / using the text file plates_to_process.txt. 

Instead, we could use the code

```
PLATES=$(ls ~/efs/${PROJECT_NAME}/${BATCH_ID}/images/ | cut -d '_' -f 1) 
```
 to create the variable; or we could create a text file containing the PLATE_IDs using 
```
ls ~/efs/${PROJECT_NAME}/${BATCH_ID}/images/ | cut -d '_' -f 1 >>  ~/efs/${PROJECT_NAME}/workspace/scratch/${BATCH_ID}/platenames.txt
```

**Comment by shntnu** [comment]
It's not clear why I ended up with two PRs #48 and #47, but I think we are good here
