### ISSUE TITLE
Conditional Travis Build

### ISSUE THREAD

**Issue by gwaybio** [cytomining/profiling-handbook#20]
Do we want to deploy the handbook for every pull request? For example, in #19, travis builds _and_ deploys the changes to the gh page at every commit. We should consider performing a [conditional build](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/) with travis to only deploy when code is merged to master. [another relevant post](https://devops.stackexchange.com/questions/3648/deploy-to-server-after-merge-to-master-branch).

**Comment by shntnu** [comment]
Indeed, we do not want to deploy for every PR. 

Conditional build  would be perfect! Would it just be adding `if: branch = master` to the .travis? Can you fix?

**Comment by gwaybio** [comment]
Yep, will do!

**Comment by gwaygenomics** [comment]
@bethac07

**Comment by gwaybio** [comment]
accidentally closed!

**Comment by gwaybio** [comment]
Still [exiting with error](https://travis-ci.org/cytomining/profiling-handbook)

> Deploying application
sh: 1: _deploy.sh: not found
Already up to date!
HEAD detached at 5864c2d
nothing to commit, working tree clean
Dropped refs/stash@{0} (3fcc1e7f25794e1faf27ea64daf5355f48e9dafb)
Script failed with status 127
failed to deploy

Will look into tomorrow

**Comment by gwaybio** [comment]
new error! But at least an error moving in the right direction

> Deploying application
Cloning into 'book-output'...
cp: cannot stat ‘../_book/*’: No such file or directory
Already up to date!
HEAD detached at 94073dc
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	book-output/
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (c93e485c243dd26e8248e761c6d7ef86b4c73bc7)
Script failed with status 1
failed to deploy

My next thought is to _also_ build on master before deploying on master

**Comment by gwaybio** [comment]
more errors:

> Output created: _book/index.html
[1] "/home/travis/build/cytomining/profiling-handbook/_book/index.html"
The command "./_build.sh" exited with 0.
cache.2
store build cache
0.00s3.62schange detected (content changed, file is created, or file is deleted):
/home/travis/R/Library/remotes/DESCRIPTION
/home/travis/R/Library/remotes/help/paths.rds
/home/travis/R/Library/remotes/help/remotes.rdb
/home/travis/R/Library/remotes/help/remotes.rdx
/home/travis/R/Library/remotes/Meta/package.rds
changes detected, packing new archive
uploading master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--R-3.5.3.tgz
cache uploaded
dpl_0
1.74s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.10.8
Parsing documentation for dpl-1.10.8
Installing ri documentation for dpl-1.10.8
Done installing documentation for dpl after 0 seconds
1 gem installed
dpl.1
Installing deploy dependencies
Successfully installed dpl-script-1.10.8
Parsing documentation for dpl-script-1.10.8
Installing ri documentation for dpl-script-1.10.8
Done installing documentation for dpl-script after 0 seconds
1 gem installed
dpl.2
Preparing deploy
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): b3d1b44 Merge pull request #25 from gwaygenomics/build-and-deploy
dpl.3
Deploying application
Cloning into 'book-output'...
cp: cannot stat ‘../_book/*’: No such file or directory
Already up to date!
HEAD detached at b3d1b44
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	book-output/
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (1f04355466591a5a2810309d8c7e354a7433b190)
Script failed with status 1
failed to deploy

Not sure what is happening now. Too much time spent on this already!

**Comment by shntnu** [comment]
Feel free to abandon if it’s too painful (and thanks for trying!)

**Comment by gwaybio** [comment]
Wooo! #26 did the trick 🎉 

https://travis-ci.org/cytomining/profiling-handbook/builds/523689507#L1081

> Output created: _book/index.html
[1] "/home/travis/build/cytomining/profiling-handbook/_book/index.html"
The command "./_build.sh" exited with 0.
cache.2
store build cache
0.00s3.72schange detected (content changed, file is created, or file is deleted):
/home/travis/R/Library/remotes/DESCRIPTION
/home/travis/R/Library/remotes/help/paths.rds
/home/travis/R/Library/remotes/help/remotes.rdb
/home/travis/R/Library/remotes/help/remotes.rdx
/home/travis/R/Library/remotes/Meta/package.rds
changes detected, packing new archive
uploading PR.26/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--R-3.5.3.tgz
cache uploaded
Done. Your build exited with 0.

**Comment by shntnu** [comment]
Congratulations 🎉
