### ISSUE TITLE
Mounting AWS Volumes in Config

### ISSUE THREAD

**Issue by gwaybio** [cytomining/profiling-handbook#28]
## Introduction

It took me a bit of troubleshooting to mount a volume as described in [step 1.1](https://cytomining.github.io/profiling-handbook/configure-environment.html). I eventually did get it to work, but the steps I used were not listed. It is possible (and even likely) that I am doing something slightly wrong that makes the instructions a bit off, but I thought it would be useful to document here:

## Troubleshooting

The error I initially received upon login after SSH'ing into the instance was:

```bash
mount.nfs4: failed to resolve server name or service not known
```

I had initially thought this was because of improper [region settings](https://docs.aws.amazon.com/efs/latest/ug/troubleshooting-efs-mounting.html) so I double checked these. They looked ok to me, so I looked into why I was getting this error on login.

I saw this line in the `.bashrc`

```
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 us-east-1a.fs-3609f37f.efs.us-east-1.amazonaws.com:/ ~/efs
```

(I also tried swapping `us-east-1a` with `us-east-1b` to no effect)

However, the volume on the AWS gui still looked like it was assigned to the correct instance.

So, after adding my credentials in an `aws configure` command, I successfully mounted the volume after following these [steps](https://devopscube.com/mount-ebs-volume-ec2-instance/). It worked! 🎉 

## Recommendation

So, not sure to what extent this solution is specific to me (maybe I configured something slightly wrong) or if it belongs in the actual handbook. Either way I thought it was useful to document.

**Comment by gwaybio** [comment]
Ah, I now see a similar set of instructions at the bottom of the page in step 1.1 that describes a similar procedure!

**Comment by shntnu** [comment]
Thanks for documenting all this!

```
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 us-east-1a.fs-3609f37f.efs.us-east-1.amazonaws.com:/ ~/efs
```

^ that line is for mounting the network file system ("EFS") whereas you want to mound a local disk ("EBS")

You've figured out how to mount an EBS, and indeed, I think you need to have created the EBS in the same region (and maybe same availability zone (AZ)?) to be able to mount.

@gwaygenomics If you can confirm that, please edit this following line appropriately (i.e. say that it should be in the same region and AZ):
https://github.com/cytomining/profiling-handbook/blob/c2b577fa17cf51abfdc957b246d3e4992c2e7549/01-config.Rmd#L96

**Comment by shntnu** [comment]
So the above is regarding EBS, but did your EFS mount ok? i.e. when you so 
`ls ~/efs/`, do you see anything? @gwaygenomics

**Comment by gwaybio** [comment]
Hmm, still new to this - didn't realize the distinction between EBS and EFS! Indeed, the project structure is there with `ls ~/efs/`

**Comment by gwaybio** [comment]
I still do get an error upon login though:

```
mount.nfs4: Failed to resolve server us-east-1a.fs-3609f37f.efs.us-east-1.amazonaws.com: Name or service not known
```

Maybe this is safe to ignore?
