### ISSUE TITLE
Document Beth's profiling workflow

### ISSUE THREAD

**Issue by bethac07** [cytomining/profiling-handbook#36]
(Tentatively as appendix B)

**Comment by shntnu** [comment]
Here's some text to add for the Broad-specific section

> Instead, you'll ssh into one of the existing Broad login servers (ssh login01 , ssh login02, etc (up through at least 04))- for file upload, I then make a tmux, run reuse UGER (for some reason this is necessary), then ish -l h_vmem=4G -pe smp 4 ; that will get you an interactive session on the cluster with 4GB of RAM and 4 CPUs (you can update those as you need, but that's what I used for my "uploading files test" and got comparable or better speeds than pirita).

**Comment by shntnu** [comment]
Moving our Slack [discussion](https://broadinstitute.slack.com/archives/G3QFQ3WQM/p1584991031026000) here.

The [Cell Painting Assay Protocol](https://docs.google.com/document/d/1gYC4a9PFuGvFuY1bY8eRLXAra5Bpt1u16O07_Ar4WU0/edit#) cites the following chapters; That presumably means that everything else in the gdoc is redundant with this handbook.

One options is to delete all other sections of this handbook (after making sure that the information is captured in the gdoc) and keep only Chapter 6.

For Chapter 6, we decide either to maintain it here, or move that as well to the gdoc.

The advantage of keeping Chapter 6 here (and delete it from the gdoc) is that eventually we expect Chapter 6 to be replaced with the workflow submodule that @gwaygenomics is creating.

What do you think @bethac07 ?



```
(Chapter 1.2)
(Chapter 1.3)
(Chapter 6.10)
(Chapter 6.2)
(Chapter 6.2.1)
(Chapter 6.2.2)
(Chapter 6.2.3)
(Chapter 6.3)
(Chapter 6.3.1)
(Chapter 6.3.2)
(Chapter 6.3.4)
(Chapter 6.3.5)
(Chapter 6.4)
(Chapter 6.4.2)
(Chapter 6.4.3)
(Chapter 6.5.1)
(Chapter 6.6)
(Chapter 6.6.2)
(Chapter 6.6.3)
(Chapter 6.7)
(Chapter 6.7.2)
(Chapter 6.7.3)
(Chapter 6.9.1)
```

**Comment by bethac07** [comment]
Realistically, I'm not the one who USES the document, so Nasim and David would have more input here than I do.

The major reason we made the google document was to be able to add more detail and explanations- stuff that the current document assumes you know.  

I think my ideal solution would be to have a version of the handbook that was more accessible to everyone, but I don't know how to do that without making it so long that it becomes clunky for the more-computational folks who already know what they're doing to read.  Collapsible notes-for-beginners sections? Is that a thing?

**Comment by shntnu** [comment]
> The major reason we made the google document was to be able to add more detail and explanations- stuff that *the current document assumes you know.*

Got it – the documentation in the handbook is certainly very sparse so maybe extra context is actually useful.

> I think my ideal solution would be to have a version of the handbook that was more accessible to everyone, but I don't know how to do that without making it so long that it becomes clunky for the more-computational folks who already know what they're doing to read. Collapsible notes-for-beginners sections? Is that a thing?

Collapsible sections do not exist unfortunately. But maybe it's sufficient that we expect the readers to navigate using the TOC, and prefix "Beginners" to sections that are for beginners. But maybe you are saying that this needs to be much more fine grained – not at the subsection level but at the paragraph level?

**Comment by bethac07** [comment]
Would none of [these ideas](https://stackoverflow.com/questions/52576626/rmarkdown-collapsible-panel) work in our current r markdown flow?

**Comment by shntnu** [comment]
> Would none of [these ideas](https://stackoverflow.com/questions/52576626/rmarkdown-collapsible-panel) work in our current r markdown flow?

Nice!

https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html

I can test it and let you know

**Comment by shntnu** [comment]
> https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html

Does not work with `bookdown` :(
https://github.com/rstudio/bookdown/issues/393#issuecomment-298697215

We have a winner! (thanks to @gwaygenomics for telling me about this)

```
To use a different region, modify the `vpc` module in the AWS infrastructure setup.

<details>
  <summary>*Click for details on AWS*</summary>
  AWS is cool!
  
</details> 
```

Here's what it looks like by default

<img width="312" alt="Screen Shot 2020-04-30 at 7 38 59 PM" src="https://user-images.githubusercontent.com/1210428/80769174-62219500-8b1a-11ea-81a1-69c009e8a660.png">

Here's when you click on it

<img width="304" alt="Screen Shot 2020-04-30 at 7 38 46 PM" src="https://user-images.githubusercontent.com/1210428/80769167-5afa8700-8b1a-11ea-96d9-94ba07b5a927.png">

**Comment by bethac07** [comment]
Huzzah!  I'll put doing this on one of my team's to-do lists, unless you're dying to do it yourself.

**Comment by shntnu** [comment]
> Huzzah! I'll put doing this on one of my team's to-do lists, unless you're dying to do it yourself.

Hurray! Feel free to tag me on PRs, if that's useful.
