### ISSUE TITLE
Look into if cytominer_scripts can be made public (keys in git history, etc)

### ISSUE THREAD

**Issue by bethac07** [cytomining/profiling-handbook#39]

**Comment by bethac07** [comment]
The nuclear option- https://tecadmin.net/delete-commit-history-in-github/

**Comment by gwaybio** [comment]
I've scanned [cytominer_scripts](https://github.com/broadinstitute/cytominer_scripts) and have determined that no sensitive information is present in any file or commit.

My process:
* I looked at [all commits](https://github.com/broadinstitute/cytominer_scripts/commits/master) with any mention of "config" or some sort of internal setting 
 *and* commits with unclear commit messages.
* I looked at all current files
* I looked at all the titles of all issues (opened and closed)

Based on the above review, no sensitive information is present

**Comment by bethac07** [comment]
👍

**Comment by gwaybio** [comment]
Potentially useful: https://github.blog/2019-08-19-github-token-scanning-one-billion-tokens-identified-and-five-new-partners/?utm_campaign=1565981113&utm_medium=social&utm_source=twitter&utm_content=1565981113

**Comment by shntnu** [comment]
Done!
https://github.com/broadinstitute/cytominer_scripts is public
