### ISSUE TITLE
Stated aggregation method (mean) is inconsistent with that used in other projects

### ISSUE THREAD

**Issue by shntnu** [cytomining/profiling-handbook#53]
The handbook uses `mean` for [aggregating](https://github.com/broadinstitute/cytominer_scripts/blob/ea1f7ea9807867c4ceab06f5e7a45a2380e0a828/aggregate.R#L40-L45) (i.e. creating level 3) as well as for [collapsing](https://github.com/broadinstitute/cytominer_scripts/blob/ea1f7ea9807867c4ceab06f5e7a45a2380e0a828/collapse.R#L76) (i.e. creating level 5). However, in other projects / papers / software, we decided to use `median`. This is a major issue and should be resolved!

Some notes

1. In the LINCS dataset, we decided  https://github.com/broadinstitute/lincs-cell-painting/issues/3#issuecomment-591994451 to use medians: we were following the lead of what was done in the [previously-processed](https://github.com/broadinstitute/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/blame/9e5832c6769760097a152b71449435262d2fcba1/analysis_log.sh) version of the dataset in which we used `median`. When [this](https://github.com/broadinstitute/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/blame/9e5832c6769760097a152b71449435262d2fcba1/analysis_log.sh#L38-L41) project was first executed in 2017, `cytominer_scripts` [used](https://github.com/broadinstitute/cytominer_scripts/blame/ea1f7ea9807867c4ceab06f5e7a45a2380e0a828/aggregate.R#L44) `median` as default; this was later changed here https://github.com/broadinstitute/cytominer_scripts/issues/18 (more on this below)
1.  [`pycytominer`](https://github.com/cytomining/pycytominer/blob/dd064c2185435e19541bafa7c976d55da15cf09e/pycytominer/aggregate.py#L40-L41) uses `median` by default for aggregation. 
1. In our 2018 [experiments](https://www.nature.com/articles/s41467-019-10154-8/figures/2), we found that `median` performed better (that plot doesn't show `mean`). 
1. This PR https://github.com/broadinstitute/cytominer_scripts/issues/18 – _Change default aggregation to be `mean` instead of `median`_  was to make `cytominer_scripts/aggregate.R` consistent with `cytotools/aggregate.R`. But it is unclear why `cytotools` (the new version of `cytominer_scripts`) used `mean`! I think this was because `cytominer::aggregate` used `mean` by [default](https://cytomining.github.io/cytominer/reference/aggregate.html).
1. Carmen Verdugo reported in June 2022: The profiling recipe does aggregation using `median` by default ([here](https://github.com/cytomining/profiling-recipe/tree/d7012751cf24e9aa1325e099b03aaf74fe2578d6#aggregate-parameters) and [here](https://github.com/cytomining/pycytominer/blob/02d05223effad9c12239ba331a8ce709153b18a4/pycytominer/cyto_utils/cells.py#L36)), while the profiling handbook uses [collate.py](https://github.com/cytomining/pycytominer/blob/1e32392b38c471013360446a5c81a882ec3823ea/pycytominer/cyto_utils/collate.py)  for the creation of the sqlite and the aggregation, and here is the key: collate.py hard-coded `mean` by default ([here](https://github.com/cytomining/pycytominer/blob/1e32392b38c471013360446a5c81a882ec3823ea/pycytominer/cyto_utils/collate.py#L226)).

**Comment by shntnu** [comment]
Moving an email conversation with @bethac07 to this thread 

IIUC the profiling recipe should be updated to reflect our current practice of using mean instead of median

- https://github.com/cytomining/profiling-recipe/blob/d7012751cf24e9aa1325e099b03aaf74fe2578d6/config_template.yml#L13
- https://github.com/cytomining/profiling-recipe/tree/d7012751cf24e9aa1325e099b03aaf74fe2578d6#aggregate-parameters

I agree with Beth that `mean` makes more sense at this level 

> The reason for that is - a lot of things may have partial penetrance (when using genetic reagents) or cause adjustments in things like cell cycle phase, which unless it affects 50% +1 cells, you'll never see that by a median aggregation. For any strong phenotype, it shouldn't matter much which you use, but one that's subtle and/or not universal we feel mean captures it better.

However we did notice this:

> * In our 2018 [experiments](https://www.nature.com/articles/s41467-019-10154-8/figures/2), we found that `median` performed better (that plot doesn't show `mean`).

Nevertheless, I think our default should just be whatever we are now doing in http://github.com/jump-cellpainting/ and whatever the Cimini lab has been using as their default. Are we using `mean` or `median` in JUMP, @bethac07. Is that consistent with whatever C-lab uses for profiling datasets? If so, let's update the recipe to reflect this

**Comment by bethac07** [comment]
>The handbook uses mean for [aggregating](https://github.com/broadinstitute/cytominer_scripts/blob/ea1f7ea9807867c4ceab06f5e7a45a2380e0a828/aggregate.R#L40-L45) (i.e. creating level 3) as well as for [collapsing](https://github.com/broadinstitute/cytominer_scripts/blob/ea1f7ea9807867c4ceab06f5e7a45a2380e0a828/collapse.R#L76) (i.e. creating level 5).

The current handbook does not cover collapsing at all, so it does not take a position on the latter, but you're right that it does in the former. 

>In our 2018 [experiments](https://www.nature.com/articles/s41467-019-10154-8/figures/2), we found that median performed better (that plot doesn't show mean)

I'm curious whether that held for both the compound experiments and TA-ORF, do you recall? Because naively, due to penetrance, I would suspect that median might fare better for compounds but mean better for genetic perturbations.


>Nevertheless, I think our default should just be whatever we are now doing in [http://github.com/jump-cellpainting/](https://github.com/jump-cellpainting/) and whatever the Cimini lab has been using as their default. Are we using mean or median in JUMP, @bethac07. Is that consistent with whatever C-lab uses for profiling datasets?

@ErinWeisbart can confirm, but I'm pretty sure at least for all of JUMP production she was using `collate.py`, which means she's been doing mean aggregation. Based on the [config files](https://github.com/jump-cellpainting/pilot-cpjump1-data/blob/main/config_files/config_compounds.yml) for CPJUMP1/the pilots, the aggregation method is not set and so would be the default, so I guess it's median. We've been using mean as our default, but if that is based on me remembering [the decision to move to mean](https://github.com/broadinstitute/cytominer_scripts/issues/18) incorrectly and thinking that was what should have been our default, we can certainly pivot to using median as the aggregation.

**Comment by bethac07** [comment]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/6721515/173593911-3030f6ae-ef47-4e7d-b466-062bf673666d.png">
It's annoying that just mean alone isn't in this graph but to my eye- 

Mean + PCA vs Median + PCA: Mean outperforms median in the bioactives + TA-ORF; they are equivalent in CDRP

Mean + Factor vs Median + Factor: The colors are maddeningly similar for this pair, and additionally it looks like the legend has 11 conditions and each plot has no more than 10, so they may never have been run head to head (or one has inadvertantly not been plotted).

So what specific data are we basing median outperforming mean on? It def isn't published, at least not in that paper.

**Comment by shntnu** [comment]
> So what specific data are we basing median outperforming mean on? It def isn't published, at least not in that paper.

Darn, I tried digging through https://broadinstitute.atlassian.net/wiki/spaces/IP/pages/506658917/Experiments+-+Moment+based+profiling to find it, but no luck

I've asked Greg in case we did it in LINCS https://github.com/broadinstitute/lincs-cell-painting/issues/22#issuecomment-1155604288

> The current handbook does not cover collapsing at all, so it does not take a position on the latter, but you're right that it does in the former.

Noted

> I'm curious whether that held for both the compound experiments and TA-ORF, do you recall? Because naively, due to penetrance, I would suspect that median might fare better for compounds but mean better for genetic perturbations.

No luck with my digging, so I don't have an answer here unfortunately

> @ErinWeisbart can confirm, but I'm pretty sure at least for all of JUMP production she was using `collate.py`, which means she's been doing mean aggregation. Based on the [config files](https://github.com/jump-cellpainting/pilot-cpjump1-data/blob/main/config_files/config_compounds.yml) for CPJUMP1/the pilots, the aggregation method is not set and so would be the default, so I guess it's median. 

Thanks for this background. So it sounds like there is a discrepancy between `jump/source_4` (`mean`) and `jump-pilot/source_4` (`median`) at the least? 

> We've been using mean as our default, but if that is based on me remembering [the decision to move to mean](https://github.com/broadinstitute/cytominer_scripts/issues/18) incorrectly and thinking that was what should have been our default, we can certainly pivot to using median as the aggregation.

1. the majority of the recent datasets have been processed using `mean`
2. `mean` is the current default in the Cimini lab
3. Even though https://github.com/cytomining/profiling-handbook/issues/53#issuecomment-1155224709 does not show mean vs median head-to-head, the PCA+mean and PCA+median should be indicative.  PCA+mean > PCA+median

All this together makes me recommend mean as the default. 

We might come up with more conclusive answers when we dig deeper into JUMP https://github.com/jump-cellpainting/develop-computational-pipeline/issues/57

**Comment by ErinWeisbart** [comment]
It is correct that for JUMP Production I used `collate.py`

**Comment by shntnu** [comment]
I'll resolve this thread now because we've concluded that `mean` is the aggregation method of choice.

As noted above, we might come up with more conclusive answers when we dig deeper into JUMP https://github.com/jump-cellpainting/develop-computational-pipeline/issues/57 and related efforts, and we can revisit these decisions then.

@niranjchandrasekaran note that there is a discrepancy between the CPJUMP1 and the JUMP production datasets; see https://github.com/cytomining/profiling-handbook/issues/53#issuecomment-1155612878 for details.

**Comment by shntnu** [comment]
Oh, and @bethac07 @ErinWeisbartL: please keep an eye out for this discrepancy; it's possible there are other places (other than the handbook+recipe) where this will need to be fixed. 

I see that @carmendv has already updated this in https://github.com/broadinstitute/cellprofiler-on-Terra (/pull/40) so that's great 👍

**Comment by AnneCarpenter** [comment]
So do I understand correctly that we are choosing mean as our future default because that is what is used in JUMP production data? If so, that makes sense to me.

**Comment by bethac07** [comment]
@AnneCarpenter Mean was used in jump-production, and we think mean is better. But all the JUMP pilots were done with median.
